services:
  - type: web
    plan: free
    name: mm-fast-backend
    env: python
    rootDir: mm-fast/api
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    buildFilter:
      paths:
        - mm-fast/api/**
  
  - type: web
    plan: free
    name: mm-fast-frontend
    env: node
    rootDir: mm-fast
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    buildFilter:
      paths:
        - mm-fast/app/**
        - mm-fast/pages/**
        - mm-fast/components/**
        - mm-fast/public/**
        - mm-fast/styles/**
        - mm-fast/next.config.mjs
