services:
  - type: web
    plan: free
    name: nextjs-frontend
    env: node
    buildCommand: cd mm-fast && npm install && npm run build
    startCommand: cd mm-fast && npm start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./mm-fast/.next
    routes:
      - type: rewrite
        source: /*
        destination: /


  - type: web
    plan: free
    name: fastapi-backend
    env: python
    buildCommand: cd mm-fast && pip install -r requirements.txt
    startCommand: cd mm-fast && uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0